// Generated by gencpp from file tek4030_visual_servoing_msgs/ImageFeaturePoints.msg
// DO NOT EDIT!


#ifndef TEK4030_VISUAL_SERVOING_MSGS_MESSAGE_IMAGEFEATUREPOINTS_H
#define TEK4030_VISUAL_SERVOING_MSGS_MESSAGE_IMAGEFEATUREPOINTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace tek4030_visual_servoing_msgs
{
template <class ContainerAllocator>
struct ImageFeaturePoints_
{
  typedef ImageFeaturePoints_<ContainerAllocator> Type;

  ImageFeaturePoints_()
    : p()  {
    }
  ImageFeaturePoints_(const ContainerAllocator& _alloc)
    : p(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _p_type;
  _p_type p;





  typedef boost::shared_ptr< ::tek4030_visual_servoing_msgs::ImageFeaturePoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tek4030_visual_servoing_msgs::ImageFeaturePoints_<ContainerAllocator> const> ConstPtr;

}; // struct ImageFeaturePoints_

typedef ::tek4030_visual_servoing_msgs::ImageFeaturePoints_<std::allocator<void> > ImageFeaturePoints;

typedef boost::shared_ptr< ::tek4030_visual_servoing_msgs::ImageFeaturePoints > ImageFeaturePointsPtr;
typedef boost::shared_ptr< ::tek4030_visual_servoing_msgs::ImageFeaturePoints const> ImageFeaturePointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tek4030_visual_servoing_msgs::ImageFeaturePoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tek4030_visual_servoing_msgs::ImageFeaturePoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tek4030_visual_servoing_msgs::ImageFeaturePoints_<ContainerAllocator1> & lhs, const ::tek4030_visual_servoing_msgs::ImageFeaturePoints_<ContainerAllocator2> & rhs)
{
  return lhs.p == rhs.p;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tek4030_visual_servoing_msgs::ImageFeaturePoints_<ContainerAllocator1> & lhs, const ::tek4030_visual_servoing_msgs::ImageFeaturePoints_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tek4030_visual_servoing_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tek4030_visual_servoing_msgs::ImageFeaturePoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tek4030_visual_servoing_msgs::ImageFeaturePoints_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tek4030_visual_servoing_msgs::ImageFeaturePoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tek4030_visual_servoing_msgs::ImageFeaturePoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tek4030_visual_servoing_msgs::ImageFeaturePoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tek4030_visual_servoing_msgs::ImageFeaturePoints_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tek4030_visual_servoing_msgs::ImageFeaturePoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74ca570665a40606dd930ab3deca3e02";
  }

  static const char* value(const ::tek4030_visual_servoing_msgs::ImageFeaturePoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74ca570665a40606ULL;
  static const uint64_t static_value2 = 0xdd930ab3deca3e02ULL;
};

template<class ContainerAllocator>
struct DataType< ::tek4030_visual_servoing_msgs::ImageFeaturePoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tek4030_visual_servoing_msgs/ImageFeaturePoints";
  }

  static const char* value(const ::tek4030_visual_servoing_msgs::ImageFeaturePoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tek4030_visual_servoing_msgs::ImageFeaturePoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point[] p\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::tek4030_visual_servoing_msgs::ImageFeaturePoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tek4030_visual_servoing_msgs::ImageFeaturePoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.p);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageFeaturePoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tek4030_visual_servoing_msgs::ImageFeaturePoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tek4030_visual_servoing_msgs::ImageFeaturePoints_<ContainerAllocator>& v)
  {
    s << indent << "p[]" << std::endl;
    for (size_t i = 0; i < v.p.size(); ++i)
    {
      s << indent << "  p[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.p[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEK4030_VISUAL_SERVOING_MSGS_MESSAGE_IMAGEFEATUREPOINTS_H
